---
######################################################################
#                                                                    #
#                             FR-EVERY-SWA1                          #
#                                                                    #
######################################################################
- name: Configuration of SWA1
  hosts: SWA1
  tasks:
    - name: SWA1 \ Modify hostname 
      community.network.nclu:
       commands:
          - add hostname FR-EVERY-SWA1
       abort: true #clean the queue
       commit: true
    - name: SWA1 \ activatoin des ports
      community.network.nclu:
       commands:
          - add int swp1,swp2,swp3,swp4,swp5
          - add interface swp5 stp bpduguard 
          - add interface swp5 stp portadminedge
       commit: true
    - name: SWA1 \ bonding setup
      community.network.nclu:
       commands:
          - add bond bond0 bond slaves swp1-2 # towards SWD
          - add bond bond1 bond slaves swp3-4 # towards NFTS SERVER
          - add bond bond0 alias Bond0(swp1-2) to SWD1 
          - add bond bond1 alias Bond1(swp3-4) to NFTS SERVER
          - add bond bond1 stp bpduguard 
          - add bond bond1 stp portadminedge

       commit: true
    - name: SWA1 \ Bridging setup
      community.network.nclu:
       commands:
          - add bridge bridge ports bond0-1
          - add bridge bridge ports swp5 # towards user
          - add bridge bridge vids 20,30,90
          - add bridge bridge pvid 99
          - add bond bond1 bridge access 90 #server NTFS  
          - add interface swp5 bridge access 20 #server NTFS 
          - add bond bond0 bridge trunk vlans 30,20,90 
       commit: true
    - name: PortSecurity setup
      community.network.nclu:
       commands:
          - add interface swp5 port-security sticky-mac
          - add interface swp5 port-security sticky-mac timeout 2000
          - add interface swp5 port-security sticky-mac aging
          - add interface swp5 port-security violation shutdown
          - add interface swp5 port-security violation timeout 3600
       commit: true    

######################################################################
#                                                                    #
#                             FR-EVERY-SWA2                          #
#                                                                    #
######################################################################
- name: Configuration of SWA2
  hosts: SWA2
  tasks:
    - name: Modify hostname 
      community.network.nclu:
       commands:
          - add hostname FR-EVERY-SWA2
       abort: true #clean the queue
       commit: true  
    - name: activatoin des ports
      community.network.nclu:
       commands:
          - add int swp1,swp2,swp3
       commit: true
    - name: bonding setup
      community.network.nclu:
       commands:
          - add bond bond0 bond slaves swp1-2 # towards SWD
          - add bond bond0 alias Bond0(swp1-2) to SWD1
       commit: true
    - name: Bridging setup
      community.network.nclu:
       commands:
          - add bridge bridge ports bond0
          - add bridge bridge ports swp3 # towards user
          - add bridge bridge vids 20,30,90
          - add bridge bridge pvid 99
          - add interface swp3 bridge access 30
          - add bond bond0 bridge trunk vlans 30,20,90 
       commit: true


######################################################################
#                                                                    #
#                             FR-EVERY-SWD1                          #
#                                                                    #
######################################################################
- name: Configuration of SWD1
  hosts: SWD1
  tasks:
    - name: Modify hostname and abort the queue before
      community.network.nclu:
       commands:
          - add hostname FR-EVERY-SWD1
       abort: true
    - name: activatoin des ports
      community.network.nclu:
       commands:
          - add int swp1,swp2,swp3,swp4
       commit: true
    - name: bonding setup
      community.network.nclu:
       commands:
          - add bond bond0 bond slaves swp1-2
          - add bond bond1 bond slaves swp3-4
          - add bond bond0 alias Bond0(swp1-2) to SWA1
          - add bond bond1 alias Bond1(swp3-4) to SWA2
       commit: true
    - name: Bridging setup
      community.network.nclu:
       commands:
          - add bridge bridge ports bond0-1
          - add bridge bridge vids 20,30,90
          - add bridge bridge pvid 99
          - add bond bond0 bridge trunk vlans 30,20,90 

       commit: true
    - name: SVI setup
      community.network.nclu:
       commands:
          - add vlan 20 ip address 192.168.2.1/24
          - add vlan 30 ip address 192.168.3.1/24
          - add vlan 90 ip address 192.168.0.1/24
       commit: true
    - name: ACL setup
      community.network.nclu:
       commands:

          #- add acl ipv4 ACL_DENY_SSH_BeetweenV20_V30 drop tcp source-ip 192.168.2.0/24 source-port any dest-ip 192.168.3.0/24 dest-port ssh
          #- add acl ipv4 ACL_DENY_SSH_BeetweenV30_V20 drop tcp source-ip 192.168.3.0/24 source-port any dest-ip 192.168.2.0/24 dest-port ssh
          
          #- add acl ipv4 ACL_DENY_ICMP_BeetweenV20_V30 drop icmp source-ip 192.168.2.0/24 dest-ip 192.168.3.0/24 
          #- add acl ipv4 ACL_DENY_ICMP_BeetweenV30_V20 drop icmp source-ip 192.168.3.0/24 dest-ip 192.168.2.0/24
          
          #- add vlan 20 acl ipv4 ACL_DENY_SSH_BeetweenV20_V30 inbound
          #- add vlan 30 acl ipv4 ACL_DENY_SSH_BeetweenV30_V20 inbound

          #- add vlan 20 acl ipv4 ACL_DENY_ICMP_BeetweenV20_V30 inbound
          #- add vlan 30 acl ipv4 ACL_DENY_ICMP_BeetweenV30_V20 inbound          
       atomic: true

